<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <AssemblyName>ItemLegacy</AssemblyName>
    <RootNamespace>ItemLegacy</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <GameInstallDir Condition="'$(GameInstallDir)' == ''">C:\Programs\Steam\steamapps\common\Slay the Spire 2</GameInstallDir>
    <GameDataDir>$(GameInstallDir)\data_sts2_windows_x86_64</GameDataDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="decompiled\**\*.cs" />
    <EmbeddedResource Remove="decompiled\**\*" />
    <None Remove="decompiled\**\*" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>$(GameDataDir)\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GameDataDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="ItemLegacy.cfg" CopyToOutputDirectory="PreserveNewest" />
    <None Include="更新日志.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
