<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <AssemblyName>ItemLegacy</AssemblyName>
    <RootNamespace>ItemLegacy</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>..\GameInstall\data_sts2_windows_x86_64\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\GameInstall\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="ItemLegacy.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
